CREATE TABLE tb_ARCHIVO
(
ID_ARCHIVO INT PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(300)
);


CREATE TABLE tb_NODO
(
ID_NODO INT PRIMARY KEY IDENTITY(1,1),
DIRECCION VARCHAR(32)
);

CREATE TABLE tb_FRAGMENTO
(
ID_ARCHIVO INT,
NOMBRE_FRAGMENTO VARCHAR(32),
ID_NODO INT,
CONSTRAINT pk_fragmento PRIMARY KEY (ID_ARCHIVO,ID_NODO),
CONSTRAINT fk_id_archivo FOREIGN KEY (ID_ARCHIVO) REFERENCES tb_ARCHIVO(ID_ARCHIVO),
CONSTRAINT fk_id_nodo FOREIGN KEY (ID_NODO) REFERENCES tb_NODO(ID_NODO)
);

CREATE TABLE tb_AUDITORIA
(
ID_AUDITORIA INT IDENTITY(1,1),
TABLE_NAME VARCHAR(32)
);


