CREATE TABLE tb_ARCHIVO
(
ID_ARCHIVO INT PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(32),
ULT_MODIFICACION VARCHAR(32),
TAMANO VARCHAR(32)
);

CREATE TABLE tb_INDEX
(
ID_INDEX INT PRIMARY KEY IDENTITY(1,1),
DIRECCION VARCHAR(32)
);

CREATE TABLE tb_ARCHIVO_INDEX
(
ID_ARCHIVO INT,
ID_INDEX INT,
CONSTRAINT pk_archivo_index PRIMARY KEY (ID_ARCHIVO, ID_INDEX),
CONSTRAINT fk_id_archivo FOREIGN KEY (ID_ARCHIVO) REFERENCES tb_ARCHIVO(ID_ARCHIVO),
CONSTRAINT fk_id_index FOREIGN KEY (ID_INDEX) REFERENCES tb_INDEX(ID_INDEX)
);